 # Pandas Series

In [1]:
import pandas as pd
a = pd.Series([1,2,3,4,5])
print(a)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [5]:
print(a.values)

[1 2 3 4 5]


In [6]:
print(a.index)

RangeIndex(start=0, stop=5, step=1)


In [67]:
data = pd.Series([2,3,4,5,6,7])
print(data)

0    2
1    3
2    4
3    5
4    6
5    7
dtype: int64


In [68]:
print(data.values)

[2 3 4 5 6 7]


In [69]:
print(data.index)

RangeIndex(start=0, stop=6, step=1)


In [13]:
section = pd.Series( [1,2,3,4,5], index=['mon', 'tue','wed','thr','fri'] )
print(section)

mon    1
tue    2
wed    3
thr    4
fri    5
dtype: int64


In [17]:
print(section [1])

2


C:\Users\AHMEE\AppData\Local\Temp\ipykernel_16980\2532567042.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(section [1])


In [19]:
print(section[ [ 1,3] ])

tue    2
thr    4
dtype: int64


C:\Users\AHMEE\AppData\Local\Temp\ipykernel_16980\304256907.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(section[ [ 1,3] ])


In [25]:
print(section[ ['mon','wed'] ])

mon    1
wed    3
dtype: int64


In [26]:
print(section[ [1,4] ])
print(section[ ['mon','wed'] ])

tue    2
fri    5
dtype: int64
mon    1
wed    3
dtype: int64


C:\Users\AHMEE\AppData\Local\Temp\ipykernel_16980\4103950000.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(section[ [1,4] ])


# For providing multipe index for selecting element in an pd Series, use Array Notation

In [28]:

print(section<4)

mon     True
tue     True
wed     True
thr    False
fri    False
dtype: bool


In [29]:
print(section[section>2])

wed    3
thr    4
fri    5
dtype: int64


In [34]:
section + 2
section = section+2
print(section)

mon    3
tue    4
wed    5
thr    6
fri    7
dtype: int64


# Taking input from numpy arrays and Converting to Pandas Series 

In [5]:
# import numpy as np
array= np.array([1,2,3,4,5])
ind = np.array(['one','tue','wed','thu','fri'])
a = pd.Series(array,ind)
print(a)

one    1
tue    2
wed    3
thu    4
fri    5
dtype: int32


In [8]:
b = np.array(['m','t','w','th'])
c = np.array([1,2,3,4])
a = pd.Series(b,c)
print(a)

1     m
2     t
3     w
4    th
dtype: object


In [9]:
print(a.values)

['m' 't' 'w' 'th']


In [10]:
print(a.index)

Index([1, 2, 3, 4], dtype='int32')


# Creating Dictionary and then Converting to pandas Series 

In [55]:

a = {"saliha":1,"lala":2,"momin":3}
b = pd.Series(a)
print(b)


saliha    1
lala      2
momin     3
dtype: int64


In [56]:
print(b.values)


[1 2 3]


In [57]:
print(b.index)

Index(['saliha', 'lala', 'momin'], dtype='object')


In [11]:
num = {1:2,3:4,5:6}
d = pd.Series(num)
print(d)

1    2
3    4
5    6
dtype: int64


# If Index more than Values

In [58]:

 # 
a = {"saliha":1, "lala":2,"momin":3}
b = pd.Series(a, index=["saliha","lala","mama","momin"])
print(b)


saliha    1.0
lala      2.0
mama      NaN
momin     3.0
dtype: float64


In [60]:
print(pd.isnull(a))

False


In [61]:
print(pd.isnull(b))

saliha    False
lala      False
mama       True
momin     False
dtype: bool


In [63]:
print(b[1])

2.0


C:\Users\AHMEE\AppData\Local\Temp\ipykernel_16980\2309727203.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(b[1])


In [64]:
print(b["saliha"])

1.0


# Different Index

In [65]:

section = pd.Series([1,2,3,4,5],index=["bad","ugly","strong","weak","good"])
print(section)

bad       1
ugly      2
strong    3
weak      4
good      5
dtype: int64


In [66]:
section.index = ["m",'t','w','th','f',]
print(section)

m     1
t     2
w     3
th    4
f     5
dtype: int64
