## Numpy

In [1]:
import numpy as np

## Zero(D) array:
- The array that contains only one value.

In [8]:
s_arr = np.array(1)
print(s_arr)
print(type(s_arr)) # to check array class

1
<class 'numpy.ndarray'>


## One (D) Array:
- They are also known as single or one dimensional array.

In [55]:
arr = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(arr)
print(len(arr)) #  to check length of array

result = np.concatenate((arr,arr2)) # Concatenation of array by using method.
print("Array after concatenation : ",result)

print("Dinmension of array is ",arr.ndim)

[1 2 3 4]
4
Array after concatenation :  [1 2 3 4 5 6 7 8]
Dinmension of array is  1


## Two (D) Array:
- The type in which elements are defined in on dimensional array.

In [25]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # Remeber that both of the sublists must be of equal length
print(arr)

print("Dinmension of array is ",arr.ndim)

# Use of `Transpose()` method 
transpose_arr = np.transpose(arr)
print("Transposed array is ")
print(transpose_arr)

# Use of `sum() method`
sum = np.sum(arr)
print("The sum will be : ",sum)

# Use of `mean()` method
mean = np.mean(arr,axis=0)
print("The mean will be : ",mean)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Dinmension of array is  2
Transposed array is 
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
The sum will be :  55
The mean will be :  [3.5 4.5 5.5 6.5 7.5]


## Use of some methods of numpy

In [43]:
d_2 = np.array([[1,2,3,4],
                [4,5,6,7],
                [8,9,10,11]])
print(d_2)
print("The shape will be : ",d_2.shape)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The shape will be :  (3, 4)


In [44]:
# use of `min()` method
min = np.min(d_2)
print("The minimum value is : ",min)

The minimum value is :  1


In [45]:
# Use of `max()` method
max = np.max(d_2)
print("Maximum value is : ",max)

Maximum value is :  11


In [46]:
#calculate standard deviation of array
sdeviation = np.std(d_2)
print("Standard deviation will be : ",sdeviation)

Standard deviation will be :  3.0776975521032313


In [47]:
# Flatten the array in single dimension by suin `ravel()` method
flatten =np.ravel(d_2)
print("Flattened array is : ",flatten)

Flattened array is :  [ 1  2  3  4  4  5  6  7  8  9 10 11]


In [48]:
# using of `Uniaue()` method 
unique = np.unique(d_2)
print("The unique elements will be : ",unique)

The unique elements will be :  [ 1  2  3  4  5  6  7  8  9 10 11]


In [52]:
# using of `cumulative_sum()` method
cumsum = np.cumsum(d_2,axis=0)
print("Cumulative sum will be ")
print(cumsum)

Cumulative sum will be 
[[ 1  2  3  4]
 [ 5  7  9 11]
 [13 16 19 22]]


In [53]:
# using of `cumulative_sum()` method
cumsum = np.cumsum(d_2,axis=1)
print("Cumulative sum will be ")
print(cumsum)

Cumulative sum will be 
[[ 1  3  6 10]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [70]:
np.argsort(d_2)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

## Perform some other methods

In [60]:
arr1 = np.array(['apple', 'banana', 'orange'])
arr1

array(['apple', 'banana', 'orange'], dtype='<U6')

In [71]:
arr = np.array([[1,2,4,'umar'],
    [5,'Eng','Umar','Attique'],
    [7,'Eng','Sir','Saeed']])
print("Shape of array is : ",arr.shape)
print("Dta type of array : ",arr.dtype)

Shape of array is :  (3, 4)
Dta type of array :  <U11


In [65]:
# 2. Count the number of elements in the array
num_elements = np.size(arr)
print("Number of elements in the array:", num_elements)

Number of elements in the array: 12


In [68]:
# Find the indices that wouls sort the array by usnig `argsort()` method
indices = np.argsort(arr)
print("Indices that would sort the array ")
indices

Indices that would sort the array 


array([[0, 1, 2, 3],
       [0, 3, 1, 2],
       [0, 1, 3, 2]], dtype=int64)

In [72]:
# replace non_numeric value in any digit you want
numeric_arr = np.where(np.char.isdigit(arr),arr,1)
print("Numeric array will be ")
print(numeric_arr)

Numeric array will be 
[['1' '2' '4' '1']
 ['5' '1' '1' '1']
 ['7' '1' '1' '1']]


In [73]:
# Convert all elements into string type
arr_str = np.char.array(arr)
print("All elements converted into string ")
print(arr_str)

All elements converted into string 
[['1' '2' '4' 'umar']
 ['5' 'Eng' 'Umar' 'Attique']
 ['7' 'Eng' 'Sir' 'Saeed']]


In [75]:
# Uniaue elements with counting
unique_elements, counts = np.unique(arr, return_counts=True)
print("\nUnique elements in the array:")
print(unique_elements)
print("Counts of unique elements:")
print(counts)


Unique elements in the array:
['1' '2' '4' '5' '7' 'Attique' 'Eng' 'Saeed' 'Sir' 'Umar' 'umar']
Counts of unique elements:
[1 1 1 1 1 1 2 1 1 1 1]


## Three(D) array

In [3]:
arr_3 = np.array([[[1,2,3,2,4],
        [4,5,6,4,2],
        [7,8,9,10,11],
        [4,6,7,4,3]]])
print(arr_3)
print("Number of dimensions : ", arr_3.ndim)

[[[ 1  2  3  2  4]
  [ 4  5  6  4  2]
  [ 7  8  9 10 11]
  [ 4  6  7  4  3]]]
Number of dimensions :  3


In [89]:
# Using of `reshape()` method
reshaped = arr_3.reshape(2,2,5)
print("Reshaped array ")
print(reshaped)

reshaped = arr_3.reshape(2,10)
print(" Other form of Reshaped array ")
print(reshaped)

Reshaped array 
[[[ 1  2  3  2  4]
  [ 4  5  6  4  2]]

 [[ 7  8  9 10 11]
  [ 4  6  7  4  3]]]
 Other form of Reshaped array 
[[ 1  2  3  2  4  4  5  6  4  2]
 [ 7  8  9 10 11  4  6  7  4  3]]


In [93]:
# generating matrix with random numbers
random_array = np.random.randint(1,11,size=(4,3))
print("Random Array is")
print(random_array)

Random Array is
[[ 1  8 10]
 [ 8  7  5]
 [ 5 10  9]
 [ 1  1  7]]


### Indexing and slicing

In [107]:
arr_3

array([[[ 1,  2,  3,  2,  4],
        [ 4,  5,  6,  4,  2],
        [ 7,  8,  9, 10, 11],
        [ 4,  6,  7,  4,  3]]])

In [5]:
import numpy as np

# Assuming arr_3 is defined like this for demonstration purposes
arr_3 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# Accessing an element
element = arr_3[0, 3]  # Accessing element at row 0, column 3
print("Element at (0, 3):", element)

# Accessing a complete row
row = arr_3[2, :]  # Accessing the complete row at index 2 (third row)
print("Complete row at index 2:", row)

# Accessing a complete column
column = arr_3[:, 1]  # Accessing the complete column at index 1 (second column)
print("Complete column at index 1:", column)


Element at (0, 3): 4
Complete row at index 2: [ 9 10 11 12]
Complete column at index 1: [ 2  6 10 14]
