## Pandas Series

In [1]:
import pandas as pd

In [6]:
series = pd.Series([1,2,3,4,5,6])
series

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [7]:
# we can add different data types 
dtypes = [1,'Umar',3,'Alam',5,'Hamzah']
pd.Series(dtypes)

0         1
1      Umar
2         3
3      Alam
4         5
5    Hamzah
dtype: object

## Pandas series ha two things as follows:
- Values.
- Index.

In [14]:
series = pd.Series([1,2,3,4,5,6])
series.values

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [15]:
series.index

RangeIndex(start=0, stop=6, step=1)

#### We can add our own indexes in our data

In [16]:
series = pd.Series([1,2,3,4,5,6],index = ['Jan','Feb','Mar','Apr','May','Jun'])
series

Jan    1
Feb    2
Mar    3
Apr    4
May    5
Jun    6
dtype: int64

In [21]:
print(series.values)
print()
print(series.index)

[1 2 3 4 5 6]

Index(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'], dtype='object')


## Create a pands series to store a student data of numbers he in each subject.

In [70]:
result = pd.Series([95,90,85,82,69,79,89,90],
                    index = ['Eng','Math','Urdu','History','Pak-study','Bio','Phy','Che'])
result

Eng          95
Math         90
Urdu         85
History      82
Pak-study    69
Bio          79
Phy          89
Che          90
dtype: int64

In [45]:
print(result['Eng'])
# to print the idex by help of value.
value = 95
index = result[result == value].index[0] # The index number must be 1 or 0 here .index[].
print(index)

95
Eng


In [51]:
print(result['Bio'])
value = 79
index = result[result == value].index[0] # The index number must be 1 or 0 here .index[]. 
print(index)

79
Bio


In [52]:
print(result['Math'])
value = 90
index = result[result == value].index[0] # The index number must be 1 or 0 here .index[].
print(index)

90
Math


In [58]:
print(result[[3,7]])
print()
print(result[['Bio','Che']])

History    82
Che        90
dtype: int64

Bio    79
Che    90
dtype: int64


## Perform comparison operator

In [63]:
print(result>80)
print()
print(result[result>80])

Eng           True
Math          True
Urdu          True
History       True
Pak-study    False
Bio          False
Phy           True
Che           True
dtype: bool

Eng        95
Math       90
Urdu       85
History    82
Phy        89
Che        90
dtype: int64


### perfrom some arithematic operator.

In [71]:
result1 = result*2
result1

Eng          190
Math         180
Urdu         170
History      164
Pak-study    138
Bio          158
Phy          178
Che          180
dtype: int64

In [72]:
result2 = result+10
result2

Eng          105
Math         100
Urdu          95
History       92
Pak-study     79
Bio           89
Phy           99
Che          100
dtype: int64

In [73]:
result3 = result/50
result3

Eng          1.90
Math         1.80
Urdu         1.70
History      1.64
Pak-study    1.38
Bio          1.58
Phy          1.78
Che          1.80
dtype: float64

In [74]:
result4 = result-50
result4

Eng          45
Math         40
Urdu         35
History      32
Pak-study    19
Bio          29
Phy          39
Che          40
dtype: int64

In [78]:
result

Eng          95
Math         90
Urdu         85
History      82
Pak-study    69
Bio          79
Phy          89
Che          90
dtype: int64

In [79]:
print('Eng' in result)
print('90' in result)

True
False


## Create numy array and convert it into pandas series.

In [80]:
import numpy as np

In [83]:
arr1 = np.array([1,4,5,6,7,8,2])
arr2 = np.array(['a','e','i','o','u','z','x'])
print(arr1,arr2)
series = pd.Series(arr2,index = arr1)
series

[1 4 5 6 7 8 2] ['a' 'e' 'i' 'o' 'u' 'z' 'x']


1    a
4    e
5    i
6    o
7    u
8    z
2    x
dtype: object

## Creating a dictionary and converting into panda series.

In [87]:
results = {'Umar':934,'Faizan':988,'Zain':844,'Asfand':681,'Saqib':937}
print(results)
print(type(results))
s_data = pd.Series(results)
print(s_data)

{'Umar': 934, 'Faizan': 988, 'Zain': 844, 'Asfand': 681, 'Saqib': 937}
<class 'dict'>
Umar      934
Faizan    988
Zain      844
Asfand    681
Saqib     937
dtype: int64


## Check if values are more then  index.

In [88]:
results = {'Umar':934,'Faizan':988,'Zain':844,'Asfand':681,'Saqib':937}
indexes = pd.Series(results,index=['Umar','Faizan','Asfand','Zain','Saqib','Mehboob','Alam'])
print(indexes)

Umar       934.0
Faizan     988.0
Asfand     681.0
Zain       844.0
Saqib      937.0
Mehboob      NaN
Alam         NaN
dtype: float64


In [89]:
indexes.isnull()

Umar       False
Faizan     False
Asfand     False
Zain       False
Saqib      False
Mehboob     True
Alam        True
dtype: bool

## Changing the indexes

In [95]:
umar = pd.Series([2,4,1,5,6,7,5,4,3],
            index = ['uma','zai','fai','asf','irf','saq','var','ban','olw'])
print(umar)
umar.index = ['u','z','f','a','i','s','v','b','o']
print(umar)

uma    2
zai    4
fai    1
asf    5
irf    6
saq    7
var    5
ban    4
olw    3
dtype: int64
u    2
z    4
f    1
a    5
i    6
s    7
v    5
b    4
o    3
dtype: int64
